site_name: 「So Proficient」 Team Wiki
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - content.code.annotate

nav:
  - Home: index.md
  - Virtual Participation:
      - 2021-2022 Russia Team Open, High School Programming Contest (VKOSHP XXII): vp/cf-gym-103483.md
      - Samara Farewell Contest 2020 (XXI Open Cup, Grand Prix of Samara): vp/cf-gym-102916.md
      - The 2021 ICPC Asia Kunming Regional Programming Contest: vp/nowcoder-32708.md
      - XXI Open Cup, Grand Prix of Korea: vp/cf-gym-102759.md
      - XXII Open Cup, Grand Prix of Southeastern Europe: vp/cf-gym-103439.md
      - XXII Open Cup, Grand Prix of Korea: vp/cf-gym-103371.md
      - 2022 Shanghai Collegiate Programming Contest: vp/cf-gym-103931.md
      - 2018-2019 9th BSUIR Open Programming Championship. Semifinal: vp/cf-gym-102439.md
      - 2019-2020 ICPC Northwestern European Regional Programming Contest (NWERC 2019): vp/cf-gym-102500.md
      - 2019-2020 ICPC Southeastern European Regional Programming Contest (SEERC 2019): vp/cf-gym-102392.md
      - 2020-2021 Russia Team Open, High School Programming Contest (VKOSHP 20): vp/cf-gym-102893.md
      - 2018-2019 9th BSUIR Open Programming Championship. Final: vp/cf-gym-102441.md
  - AtCoder:
      - AtCoder Beginner Contest:
          - AtCoder Beginner Contest G: atcoder/abc/abc-g.md
          - AtCoder Beginner Contest 229: atcoder/abc/abc229.md
          - AtCoder Beginner Contest 232: atcoder/abc/abc232.md
          - AtCoder Beginner Contest 235: atcoder/abc/abc235.md
          - AtCoder Beginner Contest 236: atcoder/abc/abc236.md
          - AtCoder Beginner Contest 241: atcoder/abc/abc241.md
          - AtCoder Beginner Contest 242: atcoder/abc/abc242.md
          - AtCoder Beginner Contest 243: atcoder/abc/abc243.md
          - AtCoder Beginner Contest 244: atcoder/abc/abc244.md
          - AtCoder Beginner Contest 245: atcoder/abc/abc245.md
          - AtCoder Beginner Contest 246: atcoder/abc/abc246.md
          - AtCoder Beginner Contest 247: atcoder/abc/abc247.md
          - AtCoder Beginner Contest 248: atcoder/abc/abc248.md
          - AtCoder Beginner Contest 249: atcoder/abc/abc249.md
          - AtCoder Beginner Contest 254: atcoder/abc/abc254.md
  - Codeforces:
      - CodeTON Round 2 (Div.1+Div.2): codeforces/cf1704.md
  - Other Contests:
      - CCPC2022网络赛: contests/ccpc-online-2022.md
      - 2022 武汉大学新生赛: contests/whu-2022-fresh.md
      - NERC2022: contests/nerc2022.md
      - 2022杭电多校(1): contests/hdu2022-1.md
      - 2022杭电多校(2): contests/hdu2022-2.md
      - 2022牛客多校(3): contests/nowcoder2022-3.md
      - 2022杭电多校(3): contests/hdu2022-3.md
      - 2022杭电多校(5): contests/hdu2022-5.md
      - 2022杭电多校(6): contests/hdu2022-6.md
      - 2022牛客多校(6): contests/nowcoder2022-6.md
      - 2022牛客多校(7): contests/nowcoder2022-7.md
      - 2022杭电多校(8): contests/hdu2022-8.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
