site_name: 「So Proficient」 Team Wiki
#theme:
#  name: material

nav:
  - Home: index.md
  - About: about.md
  - VP: vp.md
  - AtCoder: atcoder.md
  - Codeforces: codeforces.md
  - Others: contests/index.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
